import {
  InventoryItem,
  PrintOrder,
  CashTransaction,
  SupplierPayable,
  StockMutationLog,
  todayISO,
} from './types';

function offsetDateISO(daysOffset: number): string {
  const d = new Date();
  d.setDate(d.getDate() + daysOffset);
  const y = d.getFullYear();
  const m = String(d.getMonth() + 1).padStart(2, '0');
  const day = String(d.getDate()).padStart(2, '0');
  return `${y}-${m}-${day}`;
}

export function getSampleDataset(ownerId: string): {
  inventory: Omit<InventoryItem, 'createdAt' | 'updatedAt'>[];
  orders: Omit<PrintOrder, 'createdAt' | 'updatedAt'>[];
  transactions: Omit<CashTransaction, 'createdAt' | 'updatedAt'>[];
  payables: Omit<SupplierPayable, 'createdAt' | 'updatedAt'>[];
  stockLogs: Omit<StockMutationLog, 'createdAt' | 'updatedAt'>[];
} {
  const today = todayISO();
  const dMinus1 = offsetDateISO(-1);
  const dMinus2 = offsetDateISO(-2);
  const dMinus4 = offsetDateISO(-4);
  const dMinus6 = offsetDateISO(-6);
  const dMinus8 = offsetDateISO(-8);
  const dPlus2 = offsetDateISO(2);
  const dPlus7 = offsetDateISO(7);
  const dPlus14 = offsetDateISO(14);

  const inventory: Omit<InventoryItem, 'createdAt' | 'updatedAt'>[] = [
    {
      id: 'mat_flexi280',
      ownerId,
      sku: 'OUT-FLX-280',
      name: 'Flexi Frontlite China 280gr (Lebar 3.2m)',
      category: 'Bahan Outdoor',
      unit: 'm2',
      stockQty: 340,
      minStockQty: 100,
      costPerUnit: 8500,
      defaultSellPrice: 22000,
      supplierName: 'PT Sumber Media Printindo',
      location: 'Rak Roll Outdoor A-01',
    },
    {
      id: 'mat_korcin440',
      ownerId,
      sku: 'OUT-KOR-440',
      name: 'Flexi Korea China (Korcin) 440gr High-Res',
      category: 'Bahan Outdoor',
      unit: 'm2',
      stockQty: 65,
      minStockQty: 80,
      costPerUnit: 18500,
      defaultSellPrice: 45000,
      supplierName: 'PT Sumber Media Printindo',
      location: 'Rak Roll Outdoor A-02',
    },
    {
      id: 'mat_ritrama',
      ownerId,
      sku: 'IND-VNL-RTR',
      name: 'Stiker Indoor Ritrama HiRes (Glossy/Doff)',
      category: 'Bahan Indoor & Sticker',
      unit: 'm2',
      stockQty: 92,
      minStockQty: 40,
      costPerUnit: 26000,
      defaultSellPrice: 65000,
      supplierName: 'CV Grafika Mandiri Supply',
      location: 'Rak Roll Indoor B-01',
    },
    {
      id: 'mat_orajet',
      ownerId,
      sku: 'IND-VNL-ORJ',
      name: 'Stiker Indoor Orajet HiRes',
      category: 'Bahan Indoor & Sticker',
      unit: 'm2',
      stockQty: 80,
      minStockQty: 35,
      costPerUnit: 28000,
      defaultSellPrice: 70000,
      supplierName: 'CV Grafika Mandiri Supply',
      location: 'Rak Roll Indoor B-01B',
    },
    {
      id: 'mat_inflex',
      ownerId,
      sku: 'IND-VNL-INF',
      name: 'Stiker Indoor Inflex HiRes',
      category: 'Bahan Indoor & Sticker',
      unit: 'm2',
      stockQty: 110,
      minStockQty: 40,
      costPerUnit: 20000,
      defaultSellPrice: 55000,
      supplierName: 'CV Grafika Mandiri Supply',
      location: 'Rak Roll Indoor B-01C',
    },
    {
      id: 'mat_albatros',
      ownerId,
      sku: 'IND-ALB-180',
      name: 'Albatros Indoor HiRes 180gsm',
      category: 'Bahan Indoor & Sticker',
      unit: 'm2',
      stockQty: 48,
      minStockQty: 30,
      costPerUnit: 21000,
      defaultSellPrice: 55000,
      supplierName: 'CV Grafika Mandiri Supply',
      location: 'Rak Roll Indoor B-02',
    },
    {
      id: 'mat_oneway',
      ownerId,
      sku: 'IND-OWV-140',
      name: 'One Way Stiker / One Way Vision Indoor HiRes',
      category: 'Bahan Indoor & Sticker',
      unit: 'm2',
      stockQty: 60,
      minStockQty: 25,
      costPerUnit: 32000,
      defaultSellPrice: 80000,
      supplierName: 'CV Grafika Mandiri Supply',
      location: 'Rak Roll Indoor B-03',
    },
    {
      id: 'mat_ac260',
      ownerId,
      sku: 'A3P-AC-260',
      name: 'Kertas Art Carton 260gr (Ukuran Plano Potong A3+)',
      category: 'Kertas A3+ & Media',
      unit: 'Lembar',
      stockQty: 1450,
      minStockQty: 500,
      costPerUnit: 1350,
      defaultSellPrice: 5500,
      supplierName: 'Toko Kertas Sinar Jaya',
      location: 'Kabinet Kertas C-01',
    },
    {
      id: 'mat_ap150',
      ownerId,
      sku: 'A3P-AP-150',
      name: 'Kertas Art Paper 150gr (Brosur / Flyer A3+)',
      category: 'Kertas A3+ & Media',
      unit: 'Lembar',
      stockQty: 2100,
      minStockQty: 500,
      costPerUnit: 950,
      defaultSellPrice: 4000,
      supplierName: 'Toko Kertas Sinar Jaya',
      location: 'Kabinet Kertas C-02',
    },
    {
      id: 'mat_chromo',
      ownerId,
      sku: 'A3P-STC-CHR',
      name: 'Sticker Chromo Lintec A3+ (Label Kemasan)',
      category: 'Kertas A3+ & Media',
      unit: 'Lembar',
      stockQty: 320,
      minStockQty: 400,
      costPerUnit: 1800,
      defaultSellPrice: 7500,
      supplierName: 'Toko Kertas Sinar Jaya',
      location: 'Kabinet Kertas C-03',
    },
    {
      id: 'mat_ink_eco',
      ownerId,
      sku: 'INK-ECO-CMYK',
      name: 'Tinta Eco-Solvent Epson DX5/XP600 (1 Liter)',
      category: 'Tinta & Toner',
      unit: 'Liter',
      stockQty: 3,
      minStockQty: 4,
      costPerUnit: 285000,
      defaultSellPrice: 350000,
      supplierName: 'PT Sumber Media Printindo',
      location: 'Lemari Chemical D-01',
    },
    {
      id: 'mat_xbanner',
      ownerId,
      sku: 'DSP-XBN-60',
      name: 'Rangka X-Banner Fiber Hitam 60x160 cm',
      category: 'Display & Finishing',
      unit: 'Pcs',
      stockQty: 42,
      minStockQty: 20,
      costPerUnit: 24000,
      defaultSellPrice: 45000,
      supplierName: 'CV Grafika Mandiri Supply',
      location: 'Gudang Display E-01',
    },
    {
      id: 'mat_rollup',
      ownerId,
      sku: 'DSP-RLB-85',
      name: 'Rangka Roll Up Banner Aluminium 85x200 cm',
      category: 'Display & Finishing',
      unit: 'Pcs',
      stockQty: 7,
      minStockQty: 10,
      costPerUnit: 145000,
      defaultSellPrice: 235000,
      supplierName: 'CV Grafika Mandiri Supply',
      location: 'Gudang Display E-02',
    },
    {
      id: 'atk_hvs_a4',
      ownerId,
      sku: 'ATK-HVS4-107',
      name: 'Kertas HVS A4 75gr SiDU (1 Rim / 500 Lembar)',
      category: 'ATK & Perlengkapan',
      unit: 'Pack',
      stockQty: 45,
      minStockQty: 10,
      costPerUnit: 42000,
      defaultSellPrice: 55000,
      supplierName: 'Grosir ATK Nusantara',
      location: 'Etalase ATK A-01',
    },
    {
      id: 'atk_pulpen_std',
      ownerId,
      sku: 'ATK-PEN7-204',
      name: 'Pulpen Standard AE7 Hitam (Satuan / Pcs)',
      category: 'ATK & Perlengkapan',
      unit: 'Pcs',
      stockQty: 120,
      minStockQty: 24,
      costPerUnit: 1800,
      defaultSellPrice: 3500,
      supplierName: 'Grosir ATK Nusantara',
      location: 'Etalase ATK A-02',
    },
    {
      id: 'atk_map_plastik',
      ownerId,
      sku: 'ATK-MAPL-301',
      name: 'Map Plastik L / Clear Holder Dokumen',
      category: 'ATK & Perlengkapan',
      unit: 'Pcs',
      stockQty: 85,
      minStockQty: 20,
      costPerUnit: 2000,
      defaultSellPrice: 4000,
      supplierName: 'Grosir ATK Nusantara',
      location: 'Etalase ATK A-03',
    },
    {
      id: 'atk_lakban_bening',
      ownerId,
      sku: 'ATK-LKB2-408',
      name: 'Lakban Bening / Coklat Daimaru 2 Inch',
      category: 'ATK & Perlengkapan',
      unit: 'Roll',
      stockQty: 36,
      minStockQty: 10,
      costPerUnit: 11000,
      defaultSellPrice: 16000,
      supplierName: 'Grosir ATK Nusantara',
      location: 'Etalase ATK A-04',
    },
    {
      id: 'it_ssd_sata_256',
      ownerId,
      sku: 'IT-SSD-256',
      name: 'SSD SATA 2.5" 256GB (Upgrade Storage Laptop/PC)',
      category: 'Part & Storage IT',
      unit: 'Pcs',
      stockQty: 8,
      minStockQty: 3,
      costPerUnit: 285000,
      defaultSellPrice: 395000,
      supplierName: 'Distributor Komputer Jaya',
      location: 'Etalase IT & Storage S-01',
    },
    {
      id: 'it_ssd_nvme_512',
      ownerId,
      sku: 'IT-NVME-512',
      name: 'SSD M.2 NVMe PCIe 512GB (Upgrade Storage Laptop/PC)',
      category: 'Part & Storage IT',
      unit: 'Pcs',
      stockQty: 6,
      minStockQty: 2,
      costPerUnit: 520000,
      defaultSellPrice: 680000,
      supplierName: 'Distributor Komputer Jaya',
      location: 'Etalase IT & Storage S-02',
    },
    {
      id: 'it_hdd_caddy',
      ownerId,
      sku: 'IT-CAD-95',
      name: 'HDD Caddy 9.5mm / Enclosure USB 3.0 External',
      category: 'Part & Storage IT',
      unit: 'Pcs',
      stockQty: 12,
      minStockQty: 4,
      costPerUnit: 45000,
      defaultSellPrice: 85000,
      supplierName: 'Distributor Komputer Jaya',
      location: 'Etalase IT & Storage S-03',
    },
  ];

  const orders: Omit<PrintOrder, 'createdAt' | 'updatedAt'>[] = [
    {
      id: 'ord_sample_1',
      ownerId,
      invoiceNumber: 'SPK-2026-0901',
      orderDate: dMinus6,
      deadlineDate: dMinus4,
      customerName: 'Kopi Senja Nusantara',
      customerPhone: '0812-8890-1122',
      jobTitle: 'Cetak Spanduk Grand Opening 4x1.5m (15 Pcs) + Mata Ayam',
      category: 'Banner & Outdoor',
      materialId: 'mat_flexi280',
      materialName: 'Flexi Frontlite China 280gr (Lebar 3.2m)',
      unitType: 'm2',
      widthM: 4,
      heightM: 1.5,
      qty: 15,
      totalAreaOrQty: 90,
      unitPrice: 22000,
      unitCost: 8500,
      designFee: 75000,
      finishingDesc: 'Mata ayam pojok + keliling per 1 meter (90 titik)',
      finishingFee: 90000,
      discount: 45000,
      totalAmount: 2100000,
      totalCogs: 765000,
      paidAmount: 2100000,
      paymentStatus: 'Lunas',
      paymentMethod: 'Transfer Bank',
      productionStatus: 'Selesai',
      notes: 'File sudah siap cetak CMYK, lebihan putih 5cm lipat pas.',
      cashierName: 'Rina (Kasir Utama)',
    },
    {
      id: 'ord_sample_2',
      ownerId,
      invoiceNumber: 'SPK-2026-0902',
      orderDate: dMinus4,
      deadlineDate: dMinus2,
      customerName: 'Klinik Pratama Sehat Sentosa',
      customerPhone: '0813-4455-7788',
      jobTitle: 'Brosur Layanan Kesehatan A4 Lipat 3 (400 Lembar A3+ Bolak-Balik)',
      category: 'Print A3+ & Dokumen',
      materialId: 'mat_ap150',
      materialName: 'Kertas Art Paper 150gr (Brosur / Flyer A3+)',
      unitType: 'Lembar',
      widthM: 0,
      heightM: 0,
      qty: 400,
      totalAreaOrQty: 400,
      unitPrice: 4500,
      unitCost: 950,
      designFee: 150000,
      finishingDesc: 'Potong sisir + Rel lipat 3 mesin',
      finishingFee: 120000,
      discount: 0,
      totalAmount: 2070000,
      totalCogs: 380000,
      paidAmount: 2070000,
      paymentStatus: 'Lunas',
      paymentMethod: 'QRIS',
      productionStatus: 'Selesai',
      notes: 'Cetak 2 sisi (duplex) mesin Konica Minolta, warna cerah.',
      cashierName: 'Budi (Kasir Shift Sore)',
    },
    {
      id: 'ord_sample_3',
      ownerId,
      invoiceNumber: 'SPK-2026-0903',
      orderDate: dMinus2,
      deadlineDate: today,
      customerName: 'Panitia Pameran Otomotif JCC',
      customerPhone: '0811-2233-9900',
      jobTitle: 'Backdrop Event Korcin 440gr 6x3m (2 Set) + Roll Up Banner 8 Pcs',
      category: 'Banner & Outdoor',
      materialId: 'mat_korcin440',
      materialName: 'Flexi Korea China (Korcin) 440gr High-Res',
      unitType: 'm2',
      widthM: 6,
      heightM: 3,
      qty: 2,
      totalAreaOrQty: 36,
      unitPrice: 45000,
      unitCost: 18500,
      designFee: 100000,
      finishingDesc: 'Kantung pipa atas bawah + 8 Set Roll Up Aluminium lengkap',
      finishingFee: 1880000,
      discount: 100000,
      totalAmount: 3500000,
      totalCogs: 1826000,
      paidAmount: 1750000,
      paymentStatus: 'DP / Belum Lunas',
      paymentMethod: 'Transfer Bank',
      productionStatus: 'Siap Ambil',
      notes: 'DP 50% via BCA, pelunasan saat kurir ambil barang sore ini.',
      cashierName: 'Rina (Kasir Utama)',
    },
    {
      id: 'ord_sample_4',
      ownerId,
      invoiceNumber: 'SPK-2026-0904',
      orderDate: dMinus1,
      deadlineDate: dPlus2,
      customerName: 'Dapur Sambal Roa Bunda',
      customerPhone: '0857-1029-3847',
      jobTitle: 'Sticker Label Botol Sambal Chromo A3+ Kiss-Cut (250 Lembar)',
      category: 'Print A3+ & Dokumen',
      materialId: 'mat_chromo',
      materialName: 'Sticker Chromo Lintec A3+ (Label Kemasan)',
      unitType: 'Lembar',
      widthM: 0,
      heightM: 0,
      qty: 250,
      totalAreaOrQty: 250,
      unitPrice: 7500,
      unitCost: 1800,
      designFee: 50000,
      finishingDesc: 'Laminasi Glossy + Cutting Sticker Kiss-Cut Bulat 5cm',
      finishingFee: 375000,
      discount: 25000,
      totalAmount: 2275000,
      totalCogs: 450000,
      paidAmount: 1000000,
      paymentStatus: 'DP / Belum Lunas',
      paymentMethod: 'Tunai',
      productionStatus: 'Proses Cetak',
      notes: 'Pastikan sensor registration mark terbaca presisi di mesin cutting Graphtec.',
      cashierName: 'Dewi (Admin SPK)',
    },
    {
      id: 'ord_sample_5',
      ownerId,
      invoiceNumber: 'SPK-2026-0905',
      orderDate: today,
      deadlineDate: dPlus2,
      customerName: 'Dealer Motor Prima Jaya',
      customerPhone: '0818-7766-5544',
      jobTitle: 'Branding Mobil Box Sticker Vinyl Ritrama + Laminasi Doff (18 m2)',
      category: 'Indoor & Sticker',
      materialId: 'mat_ritrama',
      materialName: 'Sticker Vinyl Ritrama Glossy (Indoor/Eco-Solvent)',
      unitType: 'm2',
      widthM: 4.5,
      heightM: 2,
      qty: 2,
      totalAreaOrQty: 18,
      unitPrice: 65000,
      unitCost: 26000,
      designFee: 200000,
      finishingDesc: 'Laminasi Dingin Doff 18m2',
      finishingFee: 360000,
      discount: 0,
      totalAmount: 1730000,
      totalCogs: 468000,
      paidAmount: 0,
      paymentStatus: 'Belum Bayar',
      paymentMethod: 'Tempo',
      productionStatus: 'Antrean Desain',
      notes: 'Langganan korporat tempo 7 hari, tunggu approval layout ukuran pintu belakang.',
      cashierName: 'Rina (Kasir Utama)',
    },
  ];

  const transactions: Omit<CashTransaction, 'createdAt' | 'updatedAt'>[] = [
    {
      id: 'tx_sample_1',
      ownerId,
      txDate: dMinus6,
      referenceNo: 'KAS-IN-0901',
      type: 'Pemasukan',
      pnlGroup: 'Pendapatan Cetak',
      description: 'Pelunasan SPK-2026-0901 — Kopi Senja Nusantara (Spanduk 15 Pcs)',
      amount: 2100000,
      paymentMethod: 'Transfer Bank',
      relatedId: 'ord_sample_1',
    },
    {
      id: 'tx_sample_2',
      ownerId,
      txDate: dMinus4,
      referenceNo: 'KAS-IN-0902',
      type: 'Pemasukan',
      pnlGroup: 'Pendapatan Cetak',
      description: 'Pelunasan SPK-2026-0902 — Klinik Pratama Sehat Sentosa (Brosur A3+)',
      amount: 2070000,
      paymentMethod: 'QRIS',
      relatedId: 'ord_sample_2',
    },
    {
      id: 'tx_sample_3',
      ownerId,
      txDate: dMinus2,
      referenceNo: 'KAS-IN-0903',
      type: 'Pemasukan',
      pnlGroup: 'Pendapatan Cetak',
      description: 'Penerimaan DP 50% SPK-2026-0903 — Panitia Pameran Otomotif JCC',
      amount: 1750000,
      paymentMethod: 'Transfer Bank',
      relatedId: 'ord_sample_3',
    },
    {
      id: 'tx_sample_4',
      ownerId,
      txDate: dMinus1,
      referenceNo: 'KAS-IN-0904',
      type: 'Pemasukan',
      pnlGroup: 'Pendapatan Cetak',
      description: 'Penerimaan DP SPK-2026-0904 — Dapur Sambal Roa Bunda (Sticker Chromo)',
      amount: 1000000,
      paymentMethod: 'Tunai',
      relatedId: 'ord_sample_4',
    },
    {
      id: 'tx_sample_5',
      ownerId,
      txDate: dMinus8,
      referenceNo: 'KAS-OUT-0891',
      type: 'Pengeluaran',
      pnlGroup: 'HPP Bahan & Tinta',
      description: 'Belanja Kertas Art Paper 150gr & Art Carton 260gr (Toko Kertas Sinar Jaya)',
      amount: 1450000,
      paymentMethod: 'Transfer Bank',
      relatedId: '',
    },
    {
      id: 'tx_sample_6',
      ownerId,
      txDate: dMinus6,
      referenceNo: 'KAS-OUT-0892',
      type: 'Pengeluaran',
      pnlGroup: 'Beban Listrik & Utilitas',
      description: 'Token Listrik Workshop 3 Phase (Mesin Outdoor, Konica A3+ & AC) + Internet',
      amount: 850000,
      paymentMethod: 'Transfer Bank',
      relatedId: '',
    },
    {
      id: 'tx_sample_7',
      ownerId,
      txDate: dMinus4,
      referenceNo: 'KAS-OUT-0893',
      type: 'Pengeluaran',
      pnlGroup: 'Beban Gaji & Operator',
      description: 'Gaji Mingguan & Uang Lembur Operator Mesin Outdoor + Desainer Setting',
      amount: 1600000,
      paymentMethod: 'Tunai',
      relatedId: '',
    },
    {
      id: 'tx_sample_8',
      ownerId,
      txDate: dMinus2,
      referenceNo: 'KAS-OUT-0894',
      type: 'Pengeluaran',
      pnlGroup: 'Beban Servis & Mesin',
      description: 'Penggantian Damper, Wiper & Cleaning Solution Printhead XP600',
      amount: 325000,
      paymentMethod: 'Tunai',
      relatedId: '',
    },
  ];

  const payables: Omit<SupplierPayable, 'createdAt' | 'updatedAt'>[] = [
    {
      id: 'pay_sample_1',
      ownerId,
      supplierName: 'PT Sumber Media Printindo',
      supplierPhone: '021-5590-8811',
      invoiceNo: 'FAK-SMP-2026-441',
      txDate: dMinus6,
      dueDate: dPlus7,
      itemSummary: '3 Roll Flexi Frontlite 280gr + 4 Liter Tinta Eco-Solvent CMYK',
      totalAmount: 3650000,
      paidAmount: 1500000,
      status: 'Belum Lunas',
    },
    {
      id: 'pay_sample_2',
      ownerId,
      supplierName: 'CV Grafika Mandiri Supply',
      supplierPhone: '0812-9000-3344',
      invoiceNo: 'INV-GMS-8820',
      txDate: dMinus4,
      dueDate: dPlus14,
      itemSummary: '2 Roll Sticker Vinyl Ritrama + 30 Pcs Rangka X-Banner Fiber',
      totalAmount: 2420000,
      paidAmount: 0,
      status: 'Belum Lunas',
    },
  ];

  const stockLogs: Omit<StockMutationLog, 'createdAt' | 'updatedAt'>[] = [
    {
      id: 'log_sample_1',
      ownerId,
      logDate: dMinus6,
      materialId: 'mat_flexi280',
      materialName: 'Flexi Frontlite China 280gr (Lebar 3.2m)',
      mutationType: 'Pemakaian Produksi',
      qtyDelta: -90,
      resultingStock: 340,
      unit: 'm2',
      referenceInfo: 'Produksi SPK-2026-0901 — Kopi Senja Nusantara',
    },
    {
      id: 'log_sample_2',
      ownerId,
      logDate: dMinus4,
      materialId: 'mat_ap150',
      materialName: 'Kertas Art Paper 150gr (Brosur / Flyer A3+)',
      mutationType: 'Pemakaian Produksi',
      qtyDelta: -400,
      resultingStock: 2100,
      unit: 'Lembar',
      referenceInfo: 'Produksi SPK-2026-0902 — Klinik Pratama Sehat Sentosa',
    },
    {
      id: 'log_sample_3',
      ownerId,
      logDate: dMinus2,
      materialId: 'mat_korcin440',
      materialName: 'Flexi Korea China (Korcin) 440gr High-Res',
      mutationType: 'Pemakaian Produksi',
      qtyDelta: -36,
      resultingStock: 65,
      unit: 'm2',
      referenceInfo: 'Produksi SPK-2026-0903 — Panitia Pameran Otomotif JCC',
    },
    {
      id: 'log_sample_4',
      ownerId,
      logDate: dMinus1,
      materialId: 'mat_chromo',
      materialName: 'Sticker Chromo Lintec A3+ (Label Kemasan)',
      mutationType: 'Pemakaian Produksi',
      qtyDelta: -250,
      resultingStock: 320,
      unit: 'Lembar',
      referenceInfo: 'Produksi SPK-2026-0904 — Dapur Sambal Roa Bunda',
    },
  ];

  return { inventory, orders, transactions, payables, stockLogs };
}
